### ISSUE TITLE
Author - Image Posts

### ISSUE THREAD

**Issue by toppingart** [CMPUT404W23T05/CMPUT404-project-socialdistribution#4]
As an author, posts I create can be images.

**Comment by FunnyBot9980** [comment]
Image posts are default unlisted. When you create a normal post and add an image, on the backend there are two posts created. A normal post, and a image post. The user doesn't actually interact with the image post, it is "unlisted" and embedded in the "normal" post the user is making. However, a user may link to a image post, so you can view it. Image posts are public, just unlisted so they don't show up in timelines.
